[project]
name = "attention-visualiser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "seaborn>=0.13.2",
    "transformers>=4.51.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
    "torch>=2.7.0",
]
